-- Schema for User entity (matches com.telconovaP7F22025.demo.model.User)
-- Table: usuarios
CREATE TABLE IF NOT EXISTS usuarios (
	id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email_usuario VARCHAR(255) NOT NULL,
	password_usuario VARCHAR(255) NOT NULL,
	name_usuario VARCHAR(255) NOT NULL,
	role_usuario VARCHAR(255) NOT NULL
);

-- Unique constraint on email
ALTER TABLE usuarios ADD CONSTRAINT IF NOT EXISTS uk_usuarios_email UNIQUE (email_usuario);

-- Basic insert for verification
-- NOTE: The application uses BCrypt for passwords. This example inserts a clear-text
-- password for schema verification only. To test authentication, replace the
-- password value with a BCrypt hash (e.g. produced by BCryptPasswordEncoder).
-- Basic insert for verification (password stored as BCrypt hash so authentication works)
-- Generated with BCrypt (strength 10) for plaintext: 'secret'
INSERT INTO usuarios (email_usuario, password_usuario, name_usuario, role_usuario) VALUES (
	'test@example.com',
	'$2a$10$76jDh/40RDpBWeB/YFwSW.V/RPSBnS8AB3A7R271dWHeZyWvKOSri',
	'Test User',
	'Administrator'
);


-- Schema for Technician entity (matches com.telconovaP7F22025.demo.model.Technician)
-- Table: tecnicos
CREATE TABLE IF NOT EXISTS tecnicos (
	id_tecnico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_tecnico VARCHAR(255) NOT NULL,
	zone_tecnico VARCHAR(255) NOT NULL,
	workload_tecnico VARCHAR(255) NOT NULL,
	speciality_tecnico VARCHAR(255) NOT NULL
);

-- Unique constraint on name_tecnico
ALTER TABLE tecnicos ADD CONSTRAINT IF NOT EXISTS uk_tecnicos_name UNIQUE (name_tecnico);

-- Basic insert for verification
-- Example: Insert a technician for schema verification only
INSERT INTO tecnicos (name_tecnico, zone_tecnico, workload_tecnico, speciality_tecnico) VALUES (
	'Juan Perez',
	'Zona Oriente',
	'4',
	'Electricidad'
);

